---
name: bosh

releases:
- name: bosh
  url: http://bosh.io/d/github.com/cloudfoundry/bosh?v=256.1
  sha1: bc1538d32cd030216ac39723d363b6dc70bdcc55
- name: bosh-photon-cpi
  url: file://bosh-photon-cpi-release/releases/bosh-photon-cpi/bosh-photon-cpi-0.8.0.u1.tgz
  sha1: defa4befa93a6666fc6901813961a40cd655247d

resource_pools:
- name: vms
  network: default
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-vsphere-esxi-ubuntu-trusty-go_agent?v=3232.1
    sha1: 169df93e3e344cd84ac6ef16d76dd0276e321a25
  cloud_properties:
    vm_flavor: core-200
    disk_flavor: core-200
  env:
    bosh:
      # c1oudc0w is a default password for vcap user
      password: "$6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0"


disk_pools:
- name: disks
  disk_size: 20_000
  cloud_properties:
    disk_flavor: core-200

networks:
- name: default
  type: manual
  subnets:
  - range: 192.168.100.0/24
    gateway: 192.168.100.253
    dns: [192.168.10.1]
    cloud_properties: {name: "pg-mglab-access-vlan-100-T"}

jobs:
- name: bosh
  instances: 1

  templates:
  - {name: nats, release: bosh}
  - {name: postgres, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: powerdns, release: bosh}
  - {name: cpi, release: bosh-photon-cpi}

  resource_pool: vms
  persistent_disk_pool: disks

  networks:
  - {name: default, static_ips: [192.168.100.9]}

  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: nats-password

    postgres: &db
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: postgres-password
      database: bosh
      adapter: postgres

    redis:
      password: redis-password
      listen_addresss: 127.0.0.1
      address: 127.0.0.1

    blobstore:
      address: 192.168.100.9
      port: 25250
      provider: dav
      director: {user: director, password: director-password}
      agent: {user: agent, password: agent-password}

    director:
      address: 127.0.0.1
      name: my-bosh
      db: *db
      cpi_job: cpi
      user_management:
        provider: local
        local:
          users:
          - {name: admin, password: admin}
          - {name: hm, password: hm-password}

    hm:
      director_account: {user: admin, password: admin}
      resurrector_enabled: true

    dns:
      address: 127.0.0.1
      db: *db

    # photon job templatepwd

    photon: &photon
      target: http://PHOTON_CTRL_IP:9000
      user: dev
      password: pwd
      ignore_cert: true
      tenant: cf-test
      project: PHOTON_PROJ

    agent: {mbus: "nats://nats:nats-password@192.168.100.9:4222"}

    ntp: &ntp [0.pool.ntp.org, 1.pool.ntp.org]

cloud_provider:
  template: {name: cpi, release: bosh-photon-cpi}
  mbus: "https://mbus:mbus-password@192.168.100.9:6868"

  properties:
    agent: {mbus: "https://mbus:mbus-password@0.0.0.0:6868"}
    blobstore:
      provider: local
      options:
        blobstore_path: /var/vcap/micro_bosh/data/cache
    ntp: *ntp
    photon: *photon
