---
name: bosh

releases:
- name: bosh
  url: http://bosh.io/d/github.com/cloudfoundry/bosh?v=256.1
  sha1: bc1538d32cd030216ac39723d363b6dc70bdcc55
- name: bosh-photon-cpi
  url: https://github.com/vmware/bosh-photon-cpi-release/archive/PROMOTED-3.tar.gz
  sha1: defa4befa93a6666fc6901813961a40cd655247d

resource_pools:
- name: vms
  network: default
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-vsphere-esxi-ubuntu-trusty-go_agent?v=3232.1
    sha1: c81a8638d715ba333c6271ec402937899432ca1b
  cloud_properties:
    vm_flavor: core-200
    disk_flavor: core-200
  env:
    bosh:
      # c1oudc0w is a default password for vcap user
      password: "$6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0"


disk_pools:
- name: disks
  disk_size: 20_000
  cloud_properties:
    disk_flavor: core-200

networks:
- name: default
  type: manual
  subnets:
  - range: 192.168.100.0/24
    gateway: 192.168.100.253
    dns: [192.168.10.1]
    cloud_properties: {name: "pg-mglab-access-vlan-100-T"}

jobs:
- name: bosh
  instances: 1

  templates:
  - {name: nats, release: bosh}
  - {name: postgres, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: cpi, release: bosh-photon-cpi}

  resource_pool: vms
  persistent_disk_pool: disks

  networks:
  - {name: private, static_ips: [192.168.100.9]}

  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: nats-password

    postgres: &db
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: postgres-password
      database: bosh
      adapter: postgres

    blobstore:
      address: 192.168.100.9
      port: 25250
      provider: dav
      director: {user: director, password: director-password}
      agent: {user: agent, password: agent-password}

    director:
      address: 127.0.0.1
      name: my-bosh
      db: *db
      cpi_job: cpi
      user_management:
        provider: local
        local:
          users:
          - {name: admin, password: admin}
          - {name: hm, password: hm-password}

    hm:
      director_account: {user: admin, password: admin}
      resurrector_enabled: true

    # photon job template
    photon: &photon
      target: http://192.168.10.3:9000
      user: dev
      password: pwd
      tenant: cf-test
      project: PHOTON_PROJ
      token: eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJwaC1hZG1pbkBlc3hjbG91ZCIsImF1ZCI6WyJwaC1hZG1pbkBlc3hjbG91ZCIsInJzX2VzeGNsb3VkIl0sInNjb3BlIjoib3BlbmlkIG9mZmxpbmVfYWNjZXNzIGF0X2dyb3VwcyByc19lc3hjbG91ZCIsImlzcyI6Imh0dHBzOlwvXC8xMC4xNDYuMTcuMjFcL29wZW5pZGNvbm5lY3RcL2VzeGNsb3VkIiwiZ3JvdXBzIjpbImVzeGNsb3VkXFxzZzEiLCJlc3hjbG91ZFxcRXZlcnlvbmUiXSwidG9rZW5fY2xhc3MiOiJhY2Nlc3NfdG9rZW4iLCJ0b2tlbl90eXBlIjoiQmVhcmVyIiwiZXhwIjoxNDQ1NDA5OTYxLCJpYXQiOjE0NDQ2ODk5NjEsInRlbmFudCI6ImVzeGNsb3VkIiwianRpIjoiNjg0cU5RYUxPNFdLckhlRnBGTjhld2JOYzBEeFZfMnFGUEU3aXJ4cGp2ZyJ9.Sc085J53yECsvRCXLrDTTmeIeDwog6AEaGb6euSudOeKZ3R9V7Tc6EpRoe311zCz-6NzklaW1rOl0dszmd4ArHYp1Bikkwx71i2HEZzpbhQDx7cl_94itHdDwTUfUUo184jbx6_lzxTQDof0ueVMyYOHZIYyN7uLbHRO3nSO4fT-NzpBEvRGhSF_eKryO_UJQJxfhIu-PkhN515j6T8OuzVkxTP-AzjY2_bA6KLGbSVZWu5QDkihBLbJUOcIRUUE04pi_abid1KORFlSqQskFJze7ncUijOm62_Vv9CBvqLwUcGXwYpklx2M6nIID-L7E9dskp4b08dZf9pcfWTt7srUv204jYvapwsXKpy8TjS5iwBxnPHOdmJwcZ0suc_y7e64w-OjiZxhXj4CxFSAwUghS54yhZ26DN8tDY0skuhYRrllY-0hrMWamMHLWeGHKOwqvNuQNQC9UlQCkY_ZAVofQeTf7qovUnOFX7q8iB-hT3DpC4qay6Fd1huq0M2afhoFzEgzG5rSSf9mi4TGGntQXf34zll4y5PdFFhh8abuA1nst2Y-rfInKUXeam5gg-4Xx7OkLf0zgrR5lwh405QVG8ZhDKDccC4_8PzvTmBX1Z-vwc6b09cRAMXm7kS7ybEQpBvAV51c7Q3BwE7ZlWPcC0wAP3KWFkxj4W92P9U

    agent: {mbus: "nats://nats:nats-password@192.168.100.9:4222"}

    ntp: &ntp [0.pool.ntp.org, 1.pool.ntp.org]

cloud_provider:
  template: {name: cpi, release: bosh-photon-cpi}
  mbus: "https://mbus:mbus-password@192.168.100.9:6868"

  properties:
    agent: {mbus: "https://mbus:mbus-password@0.0.0.0:6868"}
    blobstore:
      provider: local
      options:
        blobstore_path: /var/vcap/micro_bosh/data/cache
    ntp: *ntp
    photon: *photon
