---
name: bosh

releases:
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=250
  sha1: 11b318d4ec9f0baf75d8afc6f78cf66f955d459f
- name: bosh-photon-cpi
  version: latest
  url: file:////home/ray/photon/bosh-photon-cpi-release/dev_releases/bosh-photon-cpi/bosh-photon-cpi-0.9.0+dev.1.tgz

resource_pools:
- name: vms
  network: default
  stemcell:
    url: file:////home/ray/photon/deploy-photon/bosh-stemcell-3177-vsphere-esxi-ubuntu-trusty-go_agent.tgz
    md5: 407e55fec37d1ef6a4b8e052c7da855e
  cloud_properties:
    vm_flavor: core-200
    disk_flavor: core-200

disk_pools:
- name: disks
  disk_size: 20_000
  cloud_properties:
    disk_flavor: core-200

networks:
- name: default
  type: manual
  subnets:
  - range: 10.162.35.0/19
    gateway: 10.162.63.253
    dns: [10.162.204.1]
    cloud_properties:
      network_id: 46bdadf6-3ec7-4585-b334-bec911378689

jobs:
- name: bosh
  instances: 1

  networks:
  - name: default
    static_ips: [10.162.35.199]

  templates:
  - name: nats
    release: bosh
  - name: redis
    release: bosh
  - name: blobstore
    release: bosh
  - name: postgres
    release: bosh
  - name: director
    release: bosh
  - name: health_monitor
    release: bosh
  - name: powerdns
    release: bosh
  - name: cpi
    release: bosh-photon-cpi

  resource_pool: vms
  persistent_disk_pool: disks

  properties:
    ntp: &ntp [ntp1.eng.vmware.com]

    nats:
      user: nats
      password: nats-password
      address: 127.0.0.1
      port: 4222

    blobstore:
      address: 10.162.35.199
      port: 25250
      provider: dav
      director: {user: director, password: director-password}
      agent: {user: agent, password: agent-password}
      options:
        endpoint: http://10.162.35.199:25250
        user: agent
        password: agent-password

    postgres: &db
      user: bosh
      password: bosh-password
      host: 127.0.0.1
      port: 5432
      database: bosh
      adapter: postgres

    redis:
      password: redis-password
      listen_addresss: 127.0.0.1
      address: 127.0.0.1

    director:
      name: bosh-in-esxcloud
      address: 127.0.0.1
      db: *db
      cpi_job: cpi

    hm:
      http: {user: hm, password: hm-password}
      director_account: {user: admin, password: admin}
      resurrector_enabled: true

    agent: {mbus: "nats://nats:nats-password@10.162.35.199:4222"}

    dns:
      address: 127.0.0.1
      db: *db

    # photon job template
    photon: &photon
      target: http://10.162.35.37:9000
      tenant: pcf-tenant
      project: e4fde0de-7e95-4fdf-9a49-e375646c3419

cloud_provider:
  template: {name: cpi, release: bosh-photon-cpi}
  mbus: "https://mbus:mbus-password@10.162.35.199:6868"

  properties:
    agent: {mbus: "https://mbus:mbus-password@0.0.0.0:6868"}
    blobstore:
      provider: local
      options:
        blobstore_path: /var/vcap/micro_bosh/data/cache
    ntp: *ntp
    photon: *photon
