resources:
- name: deploy-photon
  type: git
  source:
    uri: git@github.com:virtmerlin/deploy-photon.git
    branch: master
    private_key: {{githubsshkey}}

jobs:
- name: p0-WipeEnv
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: deploy-photon
      trigger: false
  - task: wipe-env
    config:
      platform: linux
      image: docker:///virtmerlin/deploy-worker
      inputs:
        - name: deploy-photon
      run:
        path: deploy-photon/ci/tasks/wipe-env.sh
      params:
        esx_user: {{esx_user}}
        esx_passwd: {{esx_passwd}}
        esx_hosts: {{esx_hosts}}
        wipe_arg: {{wipe_arg}}
